# Generated by Django 4.2.7 on 2023-11-04 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(5, "Draft"), (10, "Published")], default=5
                    ),
                ),
                ("body", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "0 - Bad"),
                            (1, "1 - Poor"),
                            (2, "2 - Draft"),
                            (3, "3 - Good"),
                            (4, "4 - Excellent"),
                            (5, "5 - Exceptional"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
